name: "🐞 Bug Report"
description: Report a bug to help improve the monitoring dashboard
title: "[BUG] Bug description"
labels: ["bug"]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ### 🐞 Bug Description
        A clear and concise description of the bug encountered.

  - type: textarea
    attributes:
      label: 🔄 Steps to Reproduce
      description: Describe the steps to reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🎯 Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ❗ Observed Behavior
      description: Describe what actually happened.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 📊 Affected Area
      description: Which area does this bug affect?
      options:
        - Dashboard Panel
        - SQL Query
        - Data Source Connection
        - Quickstart Guide
        - Other

  - type: textarea
    attributes:
      label: 🖼️ Screenshots
      description: Add screenshots if applicable.

  - type: textarea
    attributes:
      label: ℹ️ Additional Information
      description: Add any other context about the problem here.

